disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - trailing_whitespace
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - type_body_length
  - unused_optional_binding